config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resources :comments
  end
  get 'home/admin'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin_role?
      can :manage, :all
    else
      can :read, :all
      can :create, Comment
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :user, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord

	validates :downtitle,
    presence: true,
    length: {maximum: 200}

  validates :title, presence: true
  validates :body, presence: true

	has_many :comments, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:user, :body))
    redirect_to post_path(@post)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :must_be_admin, only: [:admin]

  def must_be_admin
      unless current_user && current_user.admin_role?
        redirect_to root_path, notice: "Estas página es solo disponible para el administrador"
      end
  end

  def index
    @noticia = Post.order(created_at: :desc).limit(10)
  end

  def admin
    @posts = Post.all.order(created_at: :desc)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :must_be_admin, only: [:new, :edit, :update, :destroy]

  def must_be_admin
      unless current_user && current_user.admin_role?
        redirect_to root_path, notice: "Estas página son solo disponible para el administrador"
      end
  end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :downtitle, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class= "col-md-12">
  <div class= "row">
  <p class=".p">
    <div class= "col-md-3">
      <%= comment.user %>
    </div>
    <div class= "col-md-7">
      <%= comment.body %>
    </div>
    <div class= "col-md-2">
      <%= time_ago_in_words(comment.created_at) %>
    </div>
  </p>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="sky-form" style="min-width: 350px; max-width:400px; margin:10px; ">
  <%= form_for([@post, @post.comments.build]) do |f| %>

    <fieldset>
      <section>
        <div class="input">
            Nombre de Usuario (Obligatorio)
          <%= f.text_field :user, style:"width:100%"  %>

        </div>

      </section>

      <section>
        <div class="input">
            Contenido (Obligatorio)
          <%= f.text_area :body, style:"width:100%"  %>

        </div>

      </section>
    </fieldset>
    <div class="actions">
      <%= f.submit "Enviar Comentario", class:"btn" %>
    </div>
  <% end %>
</div >

app/views/home/admin.html.erb
<style>

.table {
    width: 100%;
    max-width: 100%;
    margin-bottom: 1rem;
    background-color: transparent
}

</style>

<section class="content-section text-center" style="min-width:1000px">

<div class="back_page-2">

<div class="container_form"  style= "max-width:1020px; min-width:670px">

  <div class="col-md-10" style="margin-left:8.333%; margin-right:8.333%; ">
    <h2>Noticias </h2>

    <div class="row " style="background:rgba(229, 228, 226,0.3)">
      <div class="col-md-12">
        <table class="table">
          <thead>
            <tr>
              <th>Titulo</th>
              <th>Bajada</th>
              <th>Fecha Publicación</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @posts.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td><%= post.downtitle %></td>

                <td><%= post.created_at.strftime('%d/%b/%Y %H:%M:%S') %></td>

                <td><%= link_to 'Ver', post %></td>
                <td><%= link_to 'Editar', edit_post_path(post) %></td>
                <td><%= link_to 'Eliminar', home_admin_path, method: :delete, data: { confirm:
                  "
                  Estas eliminando la noticia:
                              "+ post.title+"
                  ¿Deseas continuar?", style: "text-align: center;" } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>


    </div>



    </div>
    <%= link_to 'Volver', root_path,class:"btn" %>

  </div>


</div>



</section>

app/views/home/index.html.erb
<!-- Intro Header -->
<style>
.p{
  margin:0 0 5px;
  width: 90%;
  font-size: 20px;
  font-family: sans-serif Verdana;
  word-wrap: break-word;
}
.col-md-12, .col-md-7,.col-md-3,.col-md-7{
  margin-top: 5px;
  margin-bottom: 5px;
  margin-left: auto;
  margin-right: auto;
  word-wrap: break-word;
}

</style>

<header class="intro">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h1 class="brand-heading">Zero Noticias</h1>
                    <p class="intro-text">Sitio de Recopilación de Noticias</p>
                    <a href="#news" class="btn btn-circle page-scroll" >
                        <i class="fa fa-angle-double-down animated"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- About Section -->
<section id="news" class=" content-section text-center" style="min-width:1000px">



          <h1>Noticias</h1>

          <% count = 0 %>
          		  <div class="row">
          		  <% @noticia.each do |noticium| %>
          		      <div class="col-md-3 text-center container" style="margin-bottom:80px;margin-left:3%; border:2px solid grey; border-radius: 10px;">
                      <h2> <%= noticium.title %> </h2>
                      <h4> <%= noticium.downtitle %> </h4>
                      <p class=".p">  <%= truncate(noticium.body.to_s, length: 503 ) { link_to "Seguir leyendo", noticium }  %> </p>
                      <%= noticium.created_at.strftime('%d/%b/%Y %H:%M:%S') %>
                      <footer>
                      <div class="row" style="background:rgba(209, 208, 206,0.25)">
                        <div class="col-md-7" >
                          Comentarios:
                          <p class=".p"> <%=  noticium.comments.count %> </p>
                        </div>
                        <div class="col-md-3" >
                          <%= link_to "Ver", noticium %>
                        </div>

                      </div>
                    </footer>
          		      </div>
          		      <% count += 1 %>
          		      <% if count == 3%>
          		        </div>
          		        <% count = 0 %>
          		        <div class="row">
          		      <%end%>
          		  <% end %>
          		  </div>




</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newspaper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://blackrockdigital.github.io/startbootstrap-grayscale/css/grayscale.min.css" rel="stylesheet">
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  </head>

  <body>
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation" style="background-color:black; opacity:0.5">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-newspaper"></i> <span class="light">Zero</span> Noticias
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="<%= root_path %>">Inicio</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="<%= posts_path %>">Diario</a>
                    </li>


                    <%- if current_user %>
                      <li>
                          <a class="page-scroll" href="<%= home_admin_path %>">Administrar</a>
                      </li>
                        <li class="nav-item">
                          <a class="nav-link" data-method="delete" rel="nofollow" href="<%= destroy_user_session_path %> "> Logout
                          </a>
                        </li>
                  <% else %>

                          <li class="nav-item ">
                            <a class="nav-link" href="<%= new_user_session_path %> "> Login
                            </a>
                          </li>


                  <%end%>


                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <%= yield %>

    <footer>
       <div class="container text-center">
           <p>Copyright &copy; ZeroNoticias S.A 2018</p>
       </div>
   </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="back_page">
  <div style="padding-top:8em;">

    <%= form_for(post) do |f| %>

      <div class="container_form">
        <div class="sky-form" style="min-width: 450px; max-width:700px; margin:10px; ">
          <header> Formulario de Noticias <%= link_to 'Volver a Home', root_path, class:"btn", style:"padding-left:30%;" %></header>

            <header> Información <header>
              <% if post.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

                  <ul>
                  <% post.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
          <fieldset>
            <section>
              <div class="input">
                Titulo de la Noticia
                <%= f.text_area :title , style:"width:100%"  %>

              </div>

            </section>

            <section>
              <div class="input">

                Bajada de la Noticia

                <%= f.text_area :downtitle, style:"width:100%" %>

              </div>
            </section>

            <section>
              <div class="input-file">
                Cuerpo de la Noticia
                <center>
                  <%= f.text_area :body, style:"width:100%" %> </center>

              </div>
            </section>

          </fieldset>





        <footer class="text-center">
          <%= f.submit "Crear", class:"btn" %>



        </footer>
        </div>
        </div>
      </div>

      <%end%>


  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<section id="news" class=" content-section text-center" style="min-width:1000px">



          <h1>Noticias</h1>

          <% count = 0 %>
          		  <div class="row">
          		  <% @posts.each do |noticium| %>
          		      <div class="col-md-3 text-center container" style="margin-bottom:80px;margin-left:3%; border:2px solid grey; border-radius: 10px;">
                      <h2> <%= noticium.title %> </h2>
                      <h4> <%= noticium.downtitle %> </h4>
                      <p class=".p">  <%= truncate(noticium.body.to_s, length: 503 ) { link_to "Seguir leyendo", noticium }  %> </p>
                      <%= noticium.created_at.strftime('%d/%b/%Y %H:%M:%S') %>
                      <footer>
                      <div class="row" style="background:rgba(209, 208, 206,0.25)">
                        <div class="col-md-7" >
                          Comentarios:
                          <p class=".p"> <%=  noticium.comments.count %> </p>
                        </div>
                        <div class="col-md-3" >
                          <%= link_to "Ver", noticium %>
                        </div>

                      </div>
                    </footer>
          		      </div>
          		      <% count += 1 %>
          		      <% if count == 3%>
          		        </div>
          		        <% count = 0 %>
          		        <div class="row">
          		      <%end%>
          		  <% end %>
          		  </div>




</section>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<style>
.p{
  margin:0 0 5px;
  width: 90%;
  font-size: 20px;
  font-family: sans-serif Verdana;
  word-wrap: break-word;
}
.col-md-12, .col-md-7,.col-md-3,.col-md-7{
  margin-top: 5px;
  margin-bottom: 5px;
  margin-left: auto;
  margin-right: auto;
  word-wrap: break-word;
}

</style>

<div class="back_page-2">
  <div style="padding-top:6em">
  </div>
<div class="container_form"  style= "max-width:1020px; min-width:670px">

  <div class="col-md-10" style="margin-left:8.333%; margin-right:8.333%; ">
    <h2> <%= @post.title %> </h2>
    <h4> <%= @post.downtitle %> </h4>
    <div class="row " style="background:rgba(229, 228, 226,0.3)">
      <div class="col-md-12">
          <p class=".p">  <%= @post.body %> </p>
      </div>


    </div>

    <div class="row" style="background:rgba(209, 208, 206,0.25)">
      <div class="col-md-12" >
        <h3>Comentarios </h3>
        <p class=".p"> <%= render @post.comments %> </p>
      </div>

    </div>

    <div class="row" style="background:rgba(229, 228, 226,0.3); min-height:110px;">
      <div class="col-md-12" >

          <h3>Añade un Comentario </h3>
            <center>
              <%= render "comments/form" %>
            </center>
      </div>


    </div>
  </div>
  <center>
<%= link_to 'Volver', root_path,class:"btn" %>
</center>
</div>


</div>